import numpy as np
import math
import random

Taa=['ALA','ARG','ASN','ASP','CYS','GLN','GLU','GLY','HIS','ILE','LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL']

Per=30
BOX=15*15*50
N_PEG=round(BOX*Per*0.01/(4*math.pi*0.8**3/3))
N_atoms=14800+N_PEG
N_one=N_atoms+9

begintime=0
Timeall=51

f=open('..\CTD_LLPS\Expand\Crowd_30\Restru.lammpstrj','r')
line=f.readlines()
Lmax=len(line)

R_pro=np.zeros([Timeall-begintime,100,148,4])     #0: type 1: x 2: y 3: z
R_cro=np.zeros([Timeall-begintime,N_PEG,4])

for i in range(Timeall-begintime):
    for j in range(N_atoms):
        sss=line[(begintime+i)*N_one+9+j].split()
        type=float(sss[1])
        index=float(sss[0])
        if type==21:
            R_cro[i][round(index-14800-1)][0]=round(type)
            R_cro[i][round(index-14800-1)][1]=float(sss[2])
            R_cro[i][round(index-14800-1)][2]=float(sss[3])
            R_cro[i][round(index-14800-1)][3]=float(sss[4])

        else:
            n_l=math.floor((index-1)/148)
            n_b=round(index-1-148*n_l)
            R_pro[i][n_l][n_b][0]=round(type)
            R_pro[i][n_l][n_b][1]=float(sss[2])
            R_pro[i][n_l][n_b][2]=float(sss[3])
            R_pro[i][n_l][n_b][3]=float(sss[4])


f_pdb=open("..\CTD_LLPS\Expand\Crowd_30\Final.pdb",'w')
for t in range(Timeall-begintime):
    f_pdb.write('REMARK    GENERATED BY python\n')
    f_pdb.write('TITLE     Macromolecule t= %d\n' %(t))
    f_pdb.write('MODEL  %d\n' %(t+1))
    for j in range(100):
        for k in range(148):
            f_pdb.write("ATOM  %5d  CA  %3s  %4d    %8.3f%8.3f%8.3f\n" %(148*j+k+1,Taa[int(R_pro[t][0][k][0]-1)],j+1,R_pro[t][j][k][1],R_pro[t][j][k][2],R_pro[t][j][k][3]))
    for n in range(N_PEG):
        f_pdb.write("ATOM  %5d  AA  %3s  %4d    %8.3f%8.3f%8.3f\n" %(14800+n+1,'PEG',100+n+1,R_cro[t][n-1][1],R_cro[t][n-1][2],R_cro[t][n-1][3]))
    f_pdb.write("TER\n")
    f_pdb.write("ENDMDL\n")
f_pdb.write("END\n")